import streamlit as st
from config import APP_TITLE, APP_ICON
from utils.auth import is_authenticated, logout_user
from utils.ui import load_custom_css

# Page Configuration
st.set_page_config(
    page_title=APP_TITLE,
    page_icon=APP_ICON,
    layout="wide",
    initial_sidebar_state="expanded"
)

def main():
    load_custom_css()
    
    # Header Section
    st.markdown(f"<h1 style='text-align: center;'>{APP_ICON} {APP_TITLE}</h1>", unsafe_allow_html=True)
    st.markdown("<p style='text-align: center; color: #6B7280; margin-bottom: 2rem;'>Your intelligent companion for data analysis and insights.</p>", unsafe_allow_html=True)
    
    if is_authenticated():
        with st.sidebar:
            st.success(f"Logged in as {st.session_state.get('user_email')}")
            if st.button("Logout", use_container_width=True):
                logout_user()
            
        st.markdown("### 🚀 Dashboard Overview")
        
        col1, col2, col3 = st.columns(3)
        
        with col1:
            with st.container(border=True):
                st.markdown("#### 📂 Upload Data")
                st.markdown("Upload your CSV files to get started with analysis.")
                if st.button("Go to Upload", use_container_width=True):
                    st.switch_page("pages/03_Upload.py")
                    
        with col2:
            with st.container(border=True):
                st.markdown("#### 📊 Data Summary")
                st.markdown("View statistics and visualizations of your data.")
                if st.button("View Summary", use_container_width=True):
                    st.switch_page("pages/04_Data_Summary.py")
                    
        with col3:
            with st.container(border=True):
                st.markdown("#### 🧠 AI Insights")
                st.markdown("Get deep insights generated by AI models.")
                if st.button("Get Insights", use_container_width=True):
                    st.switch_page("pages/05_AI_Insights.py")

        st.markdown("---")
        st.info("💡 **Tip:** Use the sidebar to navigate between different modules.")
        
    else:
        col1, col2 = st.columns([1, 1])
        
        with col1:
            st.image("https://img.freepik.com/free-vector/data-analysis-concept-illustration_114360-8023.jpg", use_column_width=True)
            
        with col2:
            st.markdown("### ✨ Features")
            
            st.markdown("""
            - **🔐 Secure Authentication**: User accounts and role management
            - **📁 File Management**: Easy CSV uploads and processing
            - **📈 Advanced Analytics**: Automatic data profiling and visualization
            - **🤖 AI Integration**: Powered by LLMs for deep insights
            """)
            
            st.markdown("### Get Started")
            b_col1, b_col2 = st.columns(2)
            with b_col1:
                if st.button("Login", type="primary", use_container_width=True):
                    st.switch_page("pages/01_Login.py")
            with b_col2:
                if st.button("Sign Up", use_container_width=True):
                    st.switch_page("pages/02_Signup.py")

if __name__ == "__main__":
    main()
